// Module included in the following assemblies:
//
// * updating/updating-cluster-within-minor.adoc
// * updating/updating-cluster-cli.adoc
// * updating/updating-cluster-rhel-compute.adoc
// * updating/updating-disconnected-cluster.adoc

[id="understanding-upgrade-channels_{context}"]

= Upgrade channels

[id="candidate-version-channel_{context}"]

ifndef::openshift-origin[]
[id="fast-version-channel_{context}"]
== fast-{product-version} channel
The `fast-{product-version}` channel is updated with new versions of {product-version} as soon as Red Hat declares the given version as a general availability (GA) release. As such, these releases are fully supported, are production quality, and have had errata notices delivered.

[id="stable-version-channel_{context}"]
== stable-{product-version} channel
While the `fast-{product-version}` channel contains releases as soon as their errata are published, releases are added to the `stable-{product-version}` channel after a delay. During this delay, data is collected from multiple sources and continuously analyzed for indications of product regressions. Once a statistically significant number of data points have been collected and absent negative signals these releases are added to the stable channel. Because the time required to
obtain a statistically significant number of data points varies based on many factors we offer no SLA for the delay duration between fast and stable channels.

Newly installed clusters default to utilizing stable channels.

[id="eus-4y-channel_{context}"]
== eus-4.y channel

In addition to the stable channel, all even-numbered minor versions of {product-title} offer an link:https://access.redhat.com/support/policy/updates/openshift#ocp4_phases[Extended Update Support] (EUS). Releases which are promoted to the stable channel are also simultaneously promoted to the EUS channels. The primary purpose of the EUS channels is to serve as a convenience for clusters performing an EUS-to-EUS upgrade. 

[NOTE]
====
Both standard and non-EUS subscribers can access all EUS repositories and necessary RPMs (`rhel-*-eus-rpms`) to be able to support critical purposes such as debugging and building drivers.
====

== candidate-{product-version} channel

The `candidate-{product-version}` channel contains releases as soon as they're produced, prior to being declared GA. Releases present only in the candidate channels have not completed full Quality Assurance testing and lack Red Hat Support. Therefore releases present only in the candidate channels are only suitable for testing purposes where destroying and recreating a cluster is acceptable. Additionally, we provide no guarantee that upgrades from these releases to GA releases will be offered.

ifdef::openshift-origin[]
[id="stable-4-channel_{context}"]
== stable-4 channel
Releases are added to the `stable-4` channel after passing all tests.

endif::openshift-origin[]

[id="upgrade-version-paths_{context}"]
== Upgrade version paths

{product-title} maintains an upgrade recommendation service that understands the version of {product-title} you have installed as well as the path to take within the channel you choose to get you to the next release.

ifndef::openshift-origin[]
You can imagine seeing the following in the `fast-{product-version}` channel:
endif::openshift-origin[]
ifdef::openshift-origin[]
You can imagine seeing the following in the `stable-4` channel:
endif::openshift-origin[]

* {product-version}.0
* {product-version}.1
* {product-version}.3
* {product-version}.4

The service recommends only upgrades that have been tested and have no serious issues. It will not suggest updating to a version of {product-title} that contains known vulnerabilities. For example, if your cluster is on {product-version}.1 and {product-title} suggests {product-version}.4, then it is safe for you to update from {product-version}.1 to {product-version}.4. Do not rely on consecutive patch numbers. In this example, {product-version}.2 is not and never was available in the channel.

ifndef::openshift-origin[]
Update stability depends on your channel. The presence of an update recommendation in the `candidate-{product-version}` channel does not imply that the update is supported. It means that no serious issues have been found with the update yet, but there might not be significant traffic through the update to suggest stability. The presence of an update recommendation in the `fast-{product-version}` or `stable-{product-version}` channels at any point is a declaration that the update is supported. While releases will never be removed from a channel, update recommendations that exhibit serious issues will be removed or made conditional from all channels. When an update recommendation is supported, it remains supported for the life of {product-version}, even if the update recommendation is later dropped or made conditional.

Red Hat will eventually provide supported update paths from any supported release in the `fast-{product-version}` or `stable-{product-version}` channels to the latest release in {product-version}.z, although there can be delays while safe paths away from troubled releases are constructed and verified.
endif::openshift-origin[]

ifdef::openshift-origin[]
The presence of an update recommendation in the `stable-4` channel at any point is a declaration that the update is supported. While releases will never be removed from the channel, update recommendations that exhibit serious issues will be removed or made conditional from all channels. When an update recommendation is supported, it remains supported for the life of {product-version}, even if the update recommendation is later dropped or made conditional.
endif::openshift-origin[]

ifndef::openshift-origin[]

[id="fast-stable-channel-strategies_{context}"]
== Fast and stable channel use and strategies

The `fast-{product-version}` and `stable-{product-version}` channels present a choice between receiving general availability releases as soon as they are available or allowing Red Hat to control the rollout of those updates. If issues are detected during rollout or at a later time, upgrades to that version might be blocked in both the `fast-{product-version}` and `stable-{product-version}` channels, and a new version might be introduced that becomes the new preferred upgrade target.

Customers can improve this process by configuring pre-production systems on the `fast-{product-version}` channel, configuring production systems on the `stable-{product-version}` channel, and participating in the Red Hat connected customer program. Red Hat uses this program to observe the impact of updates on your specific hardware and software configurations. Future releases might improve or alter the pace at which updates move from the `fast-{product-version}` to the `stable-{product-version}` channel.
endif::openshift-origin[]

[id="restricted-network-clusters_{context}"]
== Restricted network clusters

If you manage the container images for your {product-title} clusters yourself, you must consult the Red Hat errata that is associated with product releases and note any comments that impact upgrades. During upgrade, the user interface might warn you about switching between these versions, so you must ensure that you selected an appropriate version before you bypass those warnings.

ifndef::openshift-origin[]

[id="switching-between-channels_{context}"]
== Switching between channels

A channel can be switched from the web console or through the `adm upgrade channel` command:

[source,terminal]
----
$ oc adm upgrade channel <channel>
----

The web console will display an alert if you switch to a channel that does not include the current release. The web console does not recommend any updates while on a channel without the current release. You can return to the original channel at any point, however.

Changing your channel might impact the supportability of your cluster. The following conditions might apply:

* Your cluster is still supported if you change from the `stable-{product-version}` channel to the `fast-{product-version}` channel.

* You can switch to the `candidate-{product-version}` channel at any time, but some releases for this channel might be unsupported.

* You can switch from the `candidate-{product-version}` channel to the `fast-{product-version}` channel if your current release is a general availability release.

* You can always switch from the `fast-{product-version}` channel to the `stable-{product-version}` channel. There is a possible delay of up to a day for the release to be promoted to `stable-{product-version}` if the current release was recently promoted.
endif::openshift-origin[]

[id="conditional-updates-overview_{context}"]
== Conditional updates

The OpenShift Update Service might declare conditionally recommended updates associated with known risks.
The Cluster Version Operator (CVO) continually evaluates known risks associated with updates from the current {product-title} release to later releases.
When no risks apply, the update is recommended. You can update from the Administrator perspective on the web console, as well as the OpenShift CLI (`oc`).
When an update is not recommended because a risk might apply, you can view the update from the OpenShift CLI (`oc`). If the cluster administrator evaluates the potential known risks and decides it is acceptable for the current cluster, the administrator can waive the safety guards and proceed to an update.
