[[install-config-upgrading-known-issues]]
= Overview
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:prewrap!:

When upgrading your cluster there are two primary data migrations that take. The
first occurs while still running the current version and the second happens after
the upgrade completes.

If the pre-upgrade migration fails the upgrade will be halted and the admin will
need to resolve any data consistency problems before attempting the upgrade again.
If the post-upgrade migration fails the upgrade will complete and the admin should
investigate the data migration issues as soon as possible. This document will
catalog known data consistency problems and how to resolve them.


== Bug 1435132 - RoleBindingRestriction object is not deleted after namespace is deleted
Orphaned rolebindingrestrictions caused by a bug in the namespace cleanup logic that failed to clean them up when the namespace was deleted. These can be safely deleted:

=== Error
RoleBindingRestriction object is not deleted after namespace is deleted

=== Remediation
 - Get all rolebindingrestrictions across all namespaces
 - Check to see if the associated namespace exists
 - Delete the rolebindingrestriction if the namespace does not exist

+
----
IFS=$'\n'
for rbline in $(oc get rolebindingrestrictions --all-namespaces | tail -n +2); do
	ns=$(echo "$rbline" | awk '{ printf $1; }')
	name=$(echo "$rbline" | awk '{ printf $2; }')
	if ! oc get namespace "$ns"; then
		echo "Bad namespace: $ns"
		(oc create ns "$ns"; sleep 10; oc delete rolebindingrestrictions "$name" -n "$ns"; sleep 10; oc delete namespace "$ns") &
	fi
done
unset IFS
----

== Bug 1482978 - Upgrade from Openshift 3.5 to 3.6 fails when trying to storage migrate some oauthclientauthorizations
Orphaned oauthclientauthorization caused by the deletion of the associated OAuth client. These can be safely deleted

=== Error
+
----
TASK [Upgrade all storage] ******************************************************************************************************************************************************************************************************
task path: /usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml:11
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py

fatal: [egsoslosm501.linux.lan]: FAILED! => {
    "changed": true,
    "cmd": [
        "oc",
        "adm",
        "--config=/etc/origin/master/admin.kubeconfig",
        "migrate",
        "storage",
        "--include=*",
        "--confirm"
    ],
    "delta": "0:00:56.843544",
    "end": "2017-08-17 12:46:36.417413",
    "failed": true,
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "_raw_params": "oc adm --config=/etc/origin/master/admin.kubeconfig migrate storage --include=* --confirm",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        }
    },
    "rc": 1,
    "start": "2017-08-17 12:45:39.573869"
}

STDOUT:

error:     oauthclientauthorizations/H803517:system:serviceaccount:infrastruktur-test:jenkins : OAuthClientAuthorization "H803517:system:serviceaccount:infrastruktur-test:jenkins" is invalid: clientName: Internal error: system:serviceaccount:infrastruktur-test:jenkins has no redirectURIs; set serviceaccounts.openshift.io/oauth-redirecturi.<some-value>=<redirect> or create a dynamic URI using serviceaccounts.openshift.io/oauth-redirectreference.<some-value>=<reference>
summary: total=1652 errors=1 ignored=0 unchanged=1651 migrated=0
info: to rerun only failing resources, add --include=oauthclientauthorizations
error: 1 resources failed to migrate
----

=== Remediation
 - Get all oauthclientauthorizations
 - Check to see if the associated OAuth client exists (can be either an OAuth client or a service account)
 - Delete the oauthclientauthorization if the associated OAuth client does not exist

+
----
for oa in $(oc get -o name oauthclientauthorization); do
	if [[ "$oa" != *":system:serviceaccount:"* ]]; then
		client=$(echo "$oa" | cut -d : -f 2)
		query="$(oc get oauthclient $client 2>&1)"
		echo "$query" | grep NotFound
		if [ "$?" == "0" ]; then
			echo "Not found: $query"
			oc delete $oa
		fi

	fi
done

for oa in $(oc get -o name oauthclientauthorization); do
	if [[ "$oa" == *":system:serviceaccount:"* ]]; then
		ns=$(echo "$oa" | cut -d : -f 4)
		sa=$(echo "$oa" | cut -d : -f 5)
		# echo "Found: $oa -> ns:$ns  sa: $sa"
		query="$(oc get sa $sa -n $ns 2>&1)"
		echo "$query" | grep "NotFound"
		if [ "$?" == "0" ]; then
			echo "Missing sa: $sa"
			oc delete "$oa"
			echo "    Delete operation: $?"
		fi


	fi
done
----
